In [1]:
!pip install gensim

In [13]:
import gensim

In [14]:
from gensim.models import Word2Vec, KeyedVectors

## References: https://stackoverflow.com/questions/46433778/import-googlenews-vectors-negative300-bin

     

In [4]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [6]:
vec_king.shape

(300,)

In [7]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [8]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819784164429),
 ('Twenty##_cricket', 0.8068487644195557),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372579574584961),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985372543335)]

In [9]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912951469421),
 ('overjoyed', 0.6599285006523132),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437950134277344),
 ('proud', 0.6360421180725098),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269948482513428),
 ('excited', 0.6247665882110596)]

In [10]:
wv.similarity("hockey","sports")

0.5354152

In [11]:
vec=wv['king']-wv['man']+wv['woman']

In [12]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [13]:
wv.most_similar([vec])

[('king', 0.844939112663269),
 ('queen', 0.7300516366958618),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156250834465027),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.577711820602417),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376777052879333),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289886593818665)]

In [1]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.txt',
                    sep='\t',names=["label","message"])

In [2]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [3]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [5]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     c:\Users\cheta\anaconda3\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [9]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [11]:
from nltk import sent_tokenize

In [16]:
import gensim
from gensim.utils import simple_preprocess

In [17]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [18]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [19]:
import gensim

lets train word2vec from scratch

In [23]:
model=gensim.models.Word2Vec(words)

To get all vocabulary

In [24]:
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [25]:
model.corpus_count

5569

In [26]:
model.epochs

5

In [27]:
model.wv.similar_by_word('kid')

[('down', 0.9973949193954468),
 ('doe', 0.9973819851875305),
 ('stuff', 0.9973499774932861),
 ('best', 0.9972690939903259),
 ('out', 0.9972427487373352),
 ('haha', 0.997218132019043),
 ('ask', 0.9972134232521057),
 ('went', 0.9972043037414551),
 ('eat', 0.9971588850021362),
 ('dat', 0.997154951095581)]

In [28]:
model.wv.similar_by_word('good')

[('my', 0.998532772064209),
 ('happy', 0.9983704090118408),
 ('where', 0.9983574748039246),
 ('about', 0.9983240365982056),
 ('night', 0.9982585906982422),
 ('wa', 0.9982342720031738),
 ('day', 0.9982314109802246),
 ('well', 0.9982041120529175),
 ('did', 0.9981828927993774),
 ('morning', 0.9981727600097656)]

In [29]:
model.wv['good']

array([-0.28425634,  0.39620394,  0.20452827,  0.23935615,  0.12099862,
       -0.67197025,  0.3198483 ,  0.64791214, -0.46334475, -0.14759663,
       -0.23231508, -0.5396638 , -0.02201721,  0.15819162,  0.27980396,
       -0.25567704,  0.21418522, -0.38267326, -0.18232155, -0.75530183,
        0.32755476,  0.1671684 ,  0.16788234, -0.26847997, -0.069645  ,
       -0.01511936, -0.28781104, -0.3044865 , -0.42856774,  0.0719422 ,
        0.3979041 , -0.00971642,  0.1558899 , -0.23974787, -0.1665645 ,
        0.5035568 ,  0.02518347, -0.17370644, -0.14149745, -0.6555807 ,
        0.10818074, -0.30984375, -0.21907026,  0.04480949,  0.2169467 ,
       -0.0207262 , -0.14570971, -0.0498568 ,  0.29222208,  0.19556889,
        0.2655713 , -0.22042798, -0.07465343,  0.03642207, -0.05029162,
        0.10111765,  0.20886444,  0.03547451, -0.47667742,  0.27258435,
       -0.01717703,  0.18762662,  0.00466651, -0.11997627, -0.37724173,
        0.38900766,  0.14456308,  0.3819592 , -0.43274644,  0.53

In [30]:
model.wv['good'].shape

(100,)

In [31]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [34]:
import numpy as np

In [35]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [36]:

!pip install tqdm

In [44]:

from tqdm import tqdm

In [45]:
#apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))
    

  7%|▋         | 410/5569 [00:00<00:02, 1882.54it/s]c:\Users\cheta\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\cheta\anaconda3\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:02<00:00, 2651.42it/s]


In [46]:
X

[array([-1.8549934e-01,  2.7923104e-01,  1.5060572e-01,  1.6693264e-01,
         8.7067701e-02, -4.9497592e-01,  2.2000137e-01,  4.4771558e-01,
        -3.1635711e-01, -1.2515344e-01, -1.6665491e-01, -3.7361115e-01,
        -5.1149227e-02,  1.1163263e-01,  2.0139858e-01, -1.6666797e-01,
         1.2989303e-01, -2.7884972e-01, -1.3569464e-01, -5.2249080e-01,
         2.0628531e-01,  1.1134138e-01,  9.9656142e-02, -1.9649948e-01,
        -5.2432969e-02, -1.3301305e-02, -2.1558908e-01, -2.0941105e-01,
        -2.9851660e-01,  5.1301047e-02,  2.5948972e-01,  6.3278261e-03,
         8.2113713e-02, -1.7423627e-01, -1.2346341e-01,  3.5747850e-01,
         5.0263163e-02, -1.3046260e-01, -1.4056562e-01, -4.6410462e-01,
         6.6292249e-02, -2.1220089e-01, -1.7032133e-01,  2.1774940e-02,
         1.5182018e-01, -2.9268375e-02, -8.9619502e-02, -2.0461684e-02,
         2.2930963e-01,  1.3629283e-01,  1.5594806e-01, -1.7012796e-01,
        -3.6996152e-02,  4.1847862e-02, -7.5522646e-02,  6.41723

In [47]:
len(X)

5569

In [49]:
## Dependent Features
## Output Features
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values

In [50]:
y.shape

(5569,)

In [51]:
messages.shape

(5572, 2)

In [52]:
X[0].reshape(1,-1).shape

(1, 100)

In [54]:
import pandas as pd
import numpy as np

# Assuming X is a list of NumPy arrays from your previous step
list_of_dfs = [pd.DataFrame(x.reshape(1,-1)) for x in X]
df = pd.concat(list_of_dfs, ignore_index=True)

C:\Users\cheta\AppData\Local\Temp\ipykernel_15748\3601543904.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(list_of_dfs, ignore_index=True)


In [55]:

df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.185499,0.279231,0.150606,0.166933,0.087068,-0.494976,0.220001,0.447716,-0.316357,-0.125153,...,0.369501,0.175034,0.023680,0.059332,0.436840,0.163449,0.135874,-0.217786,0.154816,0.022691
1,-0.173602,0.244051,0.132165,0.145116,0.086092,-0.432730,0.181178,0.397481,-0.279542,-0.103150,...,0.330324,0.146587,0.016618,0.045916,0.372927,0.139307,0.120766,-0.200463,0.139831,0.013324
2,-0.190880,0.299510,0.159647,0.190012,0.063696,-0.527130,0.219533,0.436657,-0.328597,-0.159629,...,0.362861,0.167449,-0.001032,0.043523,0.443026,0.151460,0.076638,-0.255497,0.178551,0.051437
3,-0.262568,0.379474,0.201688,0.229318,0.124769,-0.673923,0.296256,0.618574,-0.437475,-0.161974,...,0.508024,0.236935,0.035336,0.085442,0.587325,0.226819,0.204477,-0.301745,0.211312,0.021769
4,-0.223857,0.313848,0.176547,0.190321,0.113265,-0.565931,0.246831,0.523364,-0.369177,-0.145861,...,0.429582,0.195536,0.031154,0.073066,0.495263,0.190483,0.163582,-0.264200,0.173301,0.019733


In [56]:
df['Output']=y

In [57]:

df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.185499,0.279231,0.150606,0.166933,0.087068,-0.494976,0.220001,0.447716,-0.316357,-0.125153,...,0.175034,0.023680,0.059332,0.436840,0.163449,0.135874,-0.217786,0.154816,0.022691,True
1,-0.173602,0.244051,0.132165,0.145116,0.086092,-0.432730,0.181178,0.397481,-0.279542,-0.103150,...,0.146587,0.016618,0.045916,0.372927,0.139307,0.120766,-0.200463,0.139831,0.013324,True
2,-0.190880,0.299510,0.159647,0.190012,0.063696,-0.527130,0.219533,0.436657,-0.328597,-0.159629,...,0.167449,-0.001032,0.043523,0.443026,0.151460,0.076638,-0.255497,0.178551,0.051437,False
3,-0.262568,0.379474,0.201688,0.229318,0.124769,-0.673923,0.296256,0.618574,-0.437475,-0.161974,...,0.236935,0.035336,0.085442,0.587325,0.226819,0.204477,-0.301745,0.211312,0.021769,True
4,-0.223857,0.313848,0.176547,0.190321,0.113265,-0.565931,0.246831,0.523364,-0.369177,-0.145861,...,0.195536,0.031154,0.073066,0.495263,0.190483,0.163582,-0.264200,0.173301,0.019733,True


In [58]:

df.dropna(inplace=True)

In [59]:

df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [60]:

## Independent Feature
X=df

In [61]:
X.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [62]:

y=df['Output']

In [63]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [64]:

X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
204,-0.098961,0.144311,0.083972,0.088034,0.036607,-0.251494,0.115582,0.225781,-0.168370,-0.064866,...,0.091052,0.017348,0.023326,0.224324,0.089985,0.068292,-0.119610,0.086209,0.020434,True
4656,-0.165882,0.276945,0.150704,0.178669,0.055689,-0.474557,0.208802,0.407059,-0.300289,-0.136586,...,0.166995,0.013211,0.045724,0.414344,0.140091,0.094048,-0.214174,0.156541,0.039054,False
332,-0.197751,0.292684,0.160278,0.175584,0.091819,-0.519876,0.222803,0.469055,-0.336633,-0.135157,...,0.176454,0.019498,0.057591,0.454655,0.164661,0.130099,-0.232972,0.158444,0.025548,True
1719,-0.240595,0.345927,0.189241,0.207948,0.119196,-0.620017,0.264367,0.559985,-0.404270,-0.155754,...,0.210680,0.016287,0.066730,0.530495,0.202880,0.163983,-0.286730,0.198151,0.030260,True
2951,-0.261388,0.406708,0.230535,0.256417,0.116289,-0.727669,0.307185,0.639114,-0.464882,-0.216309,...,0.236605,0.003663,0.069064,0.610123,0.217223,0.140046,-0.347153,0.216682,0.056018,True


In [65]:

y_train

204      True
4656    False
332      True
1719     True
2951     True
        ...  
5029     True
3057     True
4848     True
1581     True
1255     True
Name: Output, Length: 4445, dtype: bool

In [66]:

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [70]:
X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)

In [71]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [73]:
y_pred=classifier.predict(X_test)

In [74]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9991007194244604


In [75]:

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       1.00      0.99      1.00       151
        True       1.00      1.00      1.00       961

    accuracy                           1.00      1112
   macro avg       1.00      1.00      1.00      1112
weighted avg       1.00      1.00      1.00      1112

