Numpy

Numpy is the fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of numpy, focusing on arrays and vertorized operations.

In [1]:
import numpy as np

In [3]:
##create array using numpy
##create a 1D array

arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


1D Array

In [6]:
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5, 6]])

2D Array

In [ ]:


arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
##Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Attributes of numpy array

In [22]:
arr=np.array([[1,2,3],[4,5,6]])

print("Array: \n",arr)
print("Shape: ",arr.shape)
print("Number of dimensions: ",arr.size)
print("Size (number of elements): ", arr.size)
print("Data Type: ",arr.dtype)
print("Item size (in bytes): ",arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  6
Size (number of elements):  6
Data Type:  int32
Item size (in bytes):  4


Numpy Vectorized Operation

In [21]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element wise addition
print("Addition: ",arr1+arr2)

#Element wise substraction
print("SUbstraction: ", arr1-arr2)

#Element wise multiplication
print("Multiplication: ",arr1*arr2)

#Element wise division
print("Division: ",arr1/arr2)

Addition:  [11 22 33 44 55]
SUbstraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


Universal Function

In [25]:
arr=np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


Array Slicing and Indexing

In [26]:
arr=np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
arr[0][0]

1

In [30]:
arr[2:]

array([[10, 11, 12, 13, 14]])

In [31]:
arr[1:,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [35]:
arr[0:2,2:]

array([[3, 4, 5],
       [7, 8, 9]])

In [42]:
arr[1:2,1:4]

array([[6, 7, 8]])

Modify array elements

In [44]:
arr[0,0]=100
arr

array([[100,   2,   3,   4,   5],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [46]:
arr[1:]=100
arr

array([[100,   2,   3,   4,   5],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

Statistical Concepts-Normalization

To have a mean of 0 and standard deviation of 1

In [47]:
data=np.array([1,2,3,4,5])

Calculate the mean and standard deviation

In [48]:
mean=np.mean(data)
std_dev=np.std(data)

Normalize the data

In [49]:
normalized_data=(data-mean) / std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [50]:
data= np.array([12,3,4,5,6,7,8,9,10])

#Mean
mean=np.mean(data)
print("Mean: ",mean)

#Median
median=np.median(data)
print("Median: ",median)

#Standard Deviation
std=np.std(data)
print("std: ",std)

#Variance
var=np.var(data)
print("Mean: ",var)

Mean:  7.111111111111111
Median:  7.0
std:  2.7666443551086073
Mean:  7.65432098765432


## Logical Operation

In [51]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
data[(data>5) & (data<=8)]

array([6, 7, 8])